### ISSUE TITLE
[BUG] DockerFile Build -- suggest update to node:22-alpile

### ISSUE THREAD

**Issue by matrix303** [enricoros/big-AGI#694]
### Description

 Using `docker build -t big-agi .`, build fails because of the following error with `npm run build` in the Dockerfile.

Updating dockerfile with `FROM node:22-alpine AS base` seems to fix it

Error below:

```
=> ERROR [builder 4/5] RUN npm run build                                                                           45.9s
------
 > [builder 4/5] RUN npm run build:
#0 0.517
#0 0.517 > big-agi@1.91.0 build
#0 0.517 > next build
#0 0.517
#0 1.115  🧠 big-AGI v1.91.0 (@big-agi-2-dev)
#0 1.185    ▲ Next.js 15.1.0
#0 1.185
#0 1.197    Creating an optimized production build ...
#0 26.85  ✓ Compiled successfully
#0 26.85    Linting and checking validity of types ...
#0 44.33    Collecting page data ...
#0 45.70  ⚠ Using edge runtime on a page currently disables static generation for that page
#0 45.70 ReferenceError: CustomEvent is not defined
#0 45.70     at <unknown> (.next/server/pages/draw.js:12:6101)
#0 45.70     at t.a (.next/server/webpack-runtime.js:1:866)
#0 45.70     at 52592 (.next/server/pages/draw.js:12:4123)
#0 45.70     at t (.next/server/webpack-runtime.js:1:127)
#0 45.70     at <unknown> (.next/server/pages/draw.js:1:5442)
#0 45.70     at t.a (.next/server/webpack-runtime.js:1:866)
#0 45.70     at 7100 (.next/server/pages/draw.js:1:5343)
#0 45.70     at t (.next/server/webpack-runtime.js:1:127)
#0 45.70     at <unknown> (.next/server/pages/draw.js:1:5190)
#0 45.70     at t.a (.next/server/webpack-runtime.js:1:866)
#0 45.70
#0 45.70 > Build error occurred
#0 45.71 [Error: Failed to collect page data for /draw] { type: 'Error' }
#0 45.84 npm notice
#0 45.84 npm notice New major version of npm available! 10.8.2 -> 11.0.0
#0 45.84 npm notice Changelog: https://github.com/npm/cli/releases/tag/v11.0.0
#0 45.84 npm notice To update run: npm install -g npm@11.0.0
#0 45.84 npm notice
------
Dockerfile:33
--------------------
  31 |     # Build the application
  32 |     ENV NODE_ENV production
  33 | >>> RUN npm run build
  34 |
  35 |     # Reduce installed packages to production-only
--------------------
ERROR: failed to solve: process "/bin/sh -c npm run build" did not complete successfully: exit code: 1
```

### Device and browser

Linux

### Willingness to Contribute

- [X] 🙋‍♂️ Yes, I would like to contribute a fix.

**Comment by enricoros** [comment]
Great find - indeed it was an older node issue, with CustomEvent not defined. The upgrade is great. Thanks!
