### ISSUE TITLE
[BUG].ReferenceError: CustomEvent is not defined

### ISSUE THREAD

**Issue by wac81** [enricoros/big-AGI#710]
### Description

root@racknerd-29fa32d:~/big-AGI# npm run build

> big-agi@1.91.0 build
> next build

 🧠 big-AGI v1.91.0 (@big-agi-2-dev)
   ▲ Next.js 15.1.1
   - Environments: .env

   Creating an optimized production build ...
 ✓ Compiled successfully
 ✓ Linting and checking validity of types    
   Collecting page data  .ReferenceError: CustomEvent is not defined
    at <unknown> (.next/server/pages/draw.js:12:6101)
    at t.a (.next/server/webpack-runtime.js:1:866)
    at 52592 (.next/server/pages/draw.js:12:4123)
    at t (.next/server/webpack-runtime.js:1:127)
    at <unknown> (.next/server/pages/draw.js:1:5442)
    at t.a (.next/server/webpack-runtime.js:1:866)
    at 7100 (.next/server/pages/draw.js:1:5343)
    at t (.next/server/webpack-runtime.js:1:127)
    at <unknown> (.next/server/pages/draw.js:1:5190)
    at t.a (.next/server/webpack-runtime.js:1:866)

> Build error occurred
[Error: Failed to collect page data for /draw] { type: 'Error' }

### Device and browser

windows 11 and edge
Node.js v18.20.4

### Willingness to Contribute

- [ ] 🙋‍♂️ Yes, I would like to contribute a fix.

**Comment by enricoros** [comment]
Thanks for the report; it's probably due nodejs 18. I'll raise the requirement to 20+ (recommended 22).
